version: '2'
services:
    rabbit:
        image: "rabbitmq"
        restart: always
        ports:
          - '5672:5672'

    producer:
        build:
            context: .
            dockerfile: ProducerDockerFile
        restart: always
        depends_on:
          - rabbit

    consumer:
        build:
            context: .
            dockerfile: ConsumerDockerFile
        restart: always
        depends_on:
          - rabbit
